### PR TITLE
Fix issue #122

### PR DESCRIPTION
**Pull request by waddlaw**
Ref: #122 

My idea is replace `length` to `elasticLength` that it is calclate length is two if `**non**-ascii characters`.

Implement `elasticLength` like this:

```haskell
-- |
-- >>> elasticLength "あ"
-- 2
-- >>> elasticLength "abc"
-- 3
-- >>> elasticLength "aあa"
-- 4
elasticLength :: Text -> Int
elasticLength = Text.foldl' (\len c -> if isAscii c then len + 1 else len + 2) 0
```

I will not break anything so far.
@lspitzner Could you merge this?

### CODE REVIEW

**Comment by pythonissam** [comment]
@lspitzner This PR seems to have fixed the issue. Would you consider merging it?

**Comment by lspitzner** [comment]
Thanks for this contribution!

1. What is the additional dependency for?
2. This does not work for me. With my font, the those glyphs do not have a width of 2 ascii glyphs, so this does not give proper alignment still. Just pointing this out; If it works for you and other users I can merge still.
3. Please test this with some other alphabets/codepages and report what you tested (I don't want an additional cabal testsuite or anything, but some example that I can test manually). I highly suspect that stuff will break, because isAscii is a rather poor estimation of glyph size in general. And any unicode stuff should be tested with more than just two languages.

**Comment by lspitzner** [comment]
Closing due to inactivity, and because afaict this change makes things worse for many other languages (e.g. consider greek or russian).

**Comment by waddlaw** [comment]
@lspitzner I understand. Thank you!

**Pull request closed without merging**
