### PR TITLE
Fix infix constructor pattern matching for normal constructors

### PR DESCRIPTION
**Pull request by eborden**
Brittany was previously only supporting symbol based infix constructors. It
is common in some libraries (for example Esqueleto) to pattern match on
normal constructors as infix. Brittany was failing in this case by not
wrapping the constructor name in back ticks/spaces. Backticks and spaces
have been added in the case where the constructor contains any alpha
characters.

This addresses #101

### CODE REVIEW

**Comment by eborden** [comment]
This could be moved to the dev branch, but it seems like a simple enough fix to make it in to `master` via a point release.

**Comment by lspitzner** [comment]
Thanks! I think using `lrdrNameToTextAnn` instead of `lrdrNameToText` is a better solution, as it does not depend on `isAlpha`. And the spaces should be added unconditionally, to be consistent with operator space handling in other cases.

Please change to `dev`. I agree with making a minor release for this, but the other stuff currently on `dev` deserves to be included, too :)

**Comment by eborden** [comment]
Hmm, getting some strange business with trying to rebase off `upstream`. Seems some commits have snuck in.

**Comment by eborden** [comment]
Looks like OSX made it through the tests, but then timed out.

**Comment by eborden** [comment]
@lspitzner do you see any blockers on this PR?

**Comment by lspitzner** [comment]
Sorry for the long delay. I have effectively merged this PR now, although I think github won't see this because I rebased/cherry-picked again. But the commits are now on `dev`. I am working on a fix for #116 and will do a release once that is done.

(And you are right, the test failure is irrelevant.)

**Pull request closed without merging**
