### PR TITLE
stack.yaml: update to lts-10.0

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
Ran into issues with `cabal new-build`, so I tried stack and, since stack's ghc bindists do not work here, I updated `stack.yaml` to `lts-10.0` in order to use the local host GHC (8.2.2).

**Comment by tuncer** [comment]
One of the CI jobs fails due to the now missing extra deps, which are not needed with lts-10.0. I'd say travis-ci.yml should be adjusted.

**Comment by tfausak** [comment]
I think the typical way to do this is to have a separate `stack-lts-8.0.yaml` and use that in CI instead of setting the `--resolver`.

**Comment by tuncer** [comment]
@tfausak, pushed a commit to that effect. But, looking at the rest of the commented out travis-ci.yml, I'm not sure this is what we want, or that we'd like to carry multiple stack.yaml files at all.

**Comment by lspitzner** [comment]
Renamed the ghc-8.0 stack yaml to `stack-8.0.2.yaml`; Merged into `dev` branch
(github does not see that this is merged, probably because of the rebase and because the commits are not in `master` yet? doesn't really matter.)

Using `--resolver` only makes sense if your package always was on stackage, but that is not really an option for brittany. I think multiple stack yamls are the correct approach.

thanks!

**Pull request closed without merging**
