### PR TITLE
Tuple section support

### PR DESCRIPTION
**Pull request by matthew-piziak**
Resolves https://github.com/lspitzner/brittany/issues/41

### CODE REVIEW

**Comment by ababkin** [comment]
👍

**Comment by lspitzner** [comment]
looks good! the travis MacOS is overloaded as usual, but i trust it will be fine.

one thing: could you change merge target to dev branch please?

**Comment by matthew-piziak** [comment]
@lspitzner Done!

**Comment by lspitzner** [comment]
thanks!

**Pull request merged**
