### PR TITLE
Fix warnings when building with GHC 9.0.2

### PR DESCRIPTION
**Pull request by sergv**

### CODE REVIEW

**Comment by tfausak** [comment]
Oof, that's unfortunate. I suppose that's what I get for manually initializing `DynFlags`. 

Do you think it would be possible to use [defaultDynFlags](https://hackage.haskell.org/package/ghc-9.0.2/docs/GHC-Driver-Session.html#v:defaultDynFlags) instead?

**Comment by sergv** [comment]
I'll give `defalutDynFlags` a try.

**Comment by sergv** [comment]
@tfausak I have switched the module to using `defaultDynFlags`, now there's no need for preprocessor. It seems to work - all the tests pass.

**Review by tfausak — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
