### PR TITLE
Add stack configuration for GHC 8.6

### PR DESCRIPTION
**Pull request by tchajed**
Here's a stack configuration compatible with Stackage LTS 13.15.

This duplicates some of the features of #210 but also adds a stack configuration and the Travis configuration.

### CODE REVIEW

**Comment by jm4games** [comment]
Probably want to bump this to LTS 13.15, seeing it has bug fixes. +1 to needing this.

**Comment by tchajed** [comment]
> Probably want to bump this to LTS 13.15, seeing it has bug fixes. +1 to needing this.

Done. I didn't change the branch name to avoid moving to a new PR, so it'll just be inaccurate.

**Comment by tchajed** [comment]
Could you take a look at this PR @lspitzner? It would be nice to get brittany back on stackage.

For me the use case is that [lassik/emacs-format-all-the-code](https://github.com/lassik/emacs-format-all-the-code) uses brittany for Haskell, and Doom Emacs uses format-all-the-code for its auto-format support, so it'd be nice to install brittany using `stack install brittany` on the latest Stackage LTS.

**Comment by telser** [comment]
:+1: For this getting resolved, please!

**Comment by andys8** [comment]
Docs have to be updated, too: https://github.com/lspitzner/brittany#other-usage-notes

**Comment by lspitzner** [comment]
@andys8 good point, thanks. I have prepared an updated readme for the upcoming 0.12 release.

**Pull request merged**
